### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: 

### ISSUE THREAD

**Issue by anibal-aguila** [EmaSuriano/gatsby-starter-linkedin-resume#35]
Hi, I get:

yarn run v1.22.4
$ ts-node --files src
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: 

```
require() of ES modules is not supported.
require() of /gatsby-starter-linkedin-resume/node_modules/is-promise/index.js from /gatsby-starter-linkedin-resume/node_modules/run-async/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /gatsby-starter-linkedin-resume/node_modules/is-promise/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /gatsby-starter-linkedin-resume/node_modules/is-promise/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1149:13)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/gatsby-starter-linkedin-resume/node_modules/run-async/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by anibal-aguila** [comment]
**solved** based on
https://github.com/facebook/create-react-app/issues/8896#issuecomment-619406384


package.json

```
  "resolutions": {
    "is-promise": "2.1.0",
    "run-async/is-promise": "2.1.0"
  },
```
