### ISSUE TITLE
generate-resume: UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by anibal-aguila** [EmaSuriano/gatsby-starter-linkedin-resume#36]
node --version
v14.3.0

ref: https://github.com/linkedtales/scrapedin/issues/96#issue-621698737

```
scrapedin: 2020-05-25T17:53:40.921Z info: [profile] finished scraping url: https://www.linkedin.com/in/me
(node:2505823) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at module.exports (/gatsby-starter-linkedin-resume/node_modules/scrapedin/src/profile/cleanProfileData.js:55:81)
    at module.exports (/gatsby-starter-linkedin-resume/node_modules/scrapedin/src/profile/profile.js:76:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2505823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2505823) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

If I use new version v1.0.16
yarn add scrapedin@1.0.16 --ignore-engines

I get:

```
(node:14454) UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (/gatsby-starter-linkedin-resume/node_modules/scrapedin/node_modules/puppeteer/lib/JSHandle.js:196:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ElementHandle.click (/gatsby-starter-linkedin-resume/node_modules/scrapedin/node_modules/puppeteer/lib/JSHandle.js:248:20)
    at scrapAccomplishmentPanel (/gatsby-starter-linkedin-resume/node_modules/scrapedin/src/profile/scrapAccomplishmentPanel.js:10:5)
    at module.exports (/gatsby-starter-linkedin-resume/node_modules/scrapedin/src/profile/profile.js:50:19)
  -- ASYNC --
    at ElementHandle.<anonymous> (/gatsby-starter-linkedin-resume/node_modules/scrapedin/node_modules/puppeteer/lib/helper.js:108:27)
    at scrapAccomplishmentPanel (/gatsby-starter-linkedin-resume/node_modules/scrapedin/src/profile/scrapAccomplishmentPanel.js:10:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at module.exports (/gatsby-starter-linkedin-resume/node_modules/scrapedin/src/profile/profile.js:50:19)
```

**Comment by anibal-aguila** [comment]
alternatively this project export the resume.json: 
https://jmperezperez.com/linkedin-to-json-resume/

**Comment by EmaSuriano** [comment]
Hey, thanks for reporting the issue. The dependency of `scrapedin` was outdated, It should be fixed now!
